// Sample data for Firestore initialization
// You can use this to populate your Firestore database

final sampleProducts = [
  {
    'name': 'Matte Lipstick',
    'description': 'Long-lasting matte lipstick with rich color payoff. Perfect for all-day wear.',
    'price': 12.99,
    'imageUrl': 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=400',
    'category': 'Makeup',
    'brand': 'Maybelline',
    'rating': 4.5,
    'reviewCount': 234,
    'inStock': true,
    'tags': ['lipstick', 'matte', 'long-lasting'],
  },
  {
    'name': 'Hydrating Face Cream',
    'description': 'Deeply hydrating face cream with hyaluronic acid. Suitable for all skin types.',
    'price': 24.99,
    'imageUrl': 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
    'category': 'Skincare',
    'brand': 'L\'Oreal',
    'rating': 4.7,
    'reviewCount': 456,
    'inStock': true,
    'tags': ['moisturizer', 'hydrating', 'hyaluronic acid'],
  },
  {
    'name': 'Volumizing Mascara',
    'description': 'Lengthening and volumizing mascara for dramatic lashes.',
    'price': 9.99,
    'imageUrl': 'https://images.unsplash.com/photo-1631214558662-a2c4c76b8f3e?w=400',
    'category': 'Makeup',
    'brand': 'Revlon',
    'rating': 4.3,
    'reviewCount': 189,
    'inStock': true,
    'tags': ['mascara', 'volumizing', 'lengthening'],
  },
  {
    'name': 'Shampoo & Conditioner Set',
    'description': 'Nourishing shampoo and conditioner set for healthy, shiny hair.',
    'price': 18.99,
    'imageUrl': 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=400',
    'category': 'Hair Care',
    'brand': 'L\'Oreal',
    'rating': 4.6,
    'reviewCount': 312,
    'inStock': true,
    'tags': ['shampoo', 'conditioner', 'hair care'],
  },
  {
    'name': 'Perfume Eau de Parfum',
    'description': 'Elegant floral fragrance with notes of rose and jasmine.',
    'price': 49.99,
    'imageUrl': 'https://images.unsplash.com/photo-1541643600914-78b084683601?w=400',
    'category': 'Fragrance',
    'brand': 'Estee Lauder',
    'rating': 4.8,
    'reviewCount': 567,
    'inStock': true,
    'tags': ['perfume', 'floral', 'elegant'],
  },
  {
    'name': 'Nail Polish Set',
    'description': 'Set of 6 vibrant nail polish colors with long-lasting formula.',
    'price': 15.99,
    'imageUrl': 'https://images.unsplash.com/photo-1604654894610-df63bc536371?w=400',
    'category': 'Nail Care',
    'brand': 'Revlon',
    'rating': 4.4,
    'reviewCount': 278,
    'inStock': true,
    'tags': ['nail polish', 'set', 'long-lasting'],
  },
  {
    'name': 'BB Cream',
    'description': 'All-in-one BB cream with SPF 30. Provides coverage and sun protection.',
    'price': 16.99,
    'imageUrl': 'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=400',
    'category': 'Makeup',
    'brand': 'Maybelline',
    'rating': 4.5,
    'reviewCount': 423,
    'inStock': true,
    'tags': ['bb cream', 'spf', 'coverage'],
  },
  {
    'name': 'Body Lotion',
    'description': 'Moisturizing body lotion with shea butter and vitamin E.',
    'price': 11.99,
    'imageUrl': 'https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400',
    'category': 'Body Care',
    'brand': 'NARS',
    'rating': 4.6,
    'reviewCount': 345,
    'inStock': true,
    'tags': ['body lotion', 'moisturizing', 'shea butter'],
  },
];

